### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by JoshVarga** [rustyoz/svg#2]
I was about to start writing my own SVG parser and just happened to find this one. I know you just got it out here and are just getting things situated, but I wanted to give it a shot.

I pulled it down and tried running, the build failed due to the fact that the code at "github.com/rustyoz/genericlexer" is missing. Is this code that you overlooked? Are planning to put up on github?

**Comment by rustyoz** [comment]
Hi @JoshVarga 
Sorry about that, I have just pushed the other code to a git repo and I set up a travis-ci build to check it. 
It should be all working now. 

At the moment this svg parser does most of what I require it to do, but it is far from complete. Any help on pushing it forward is appreciated
